### ISSUE TITLE
ios13.3（模拟器 11） 语音消息无法送达

### ISSUE THREAD

**Issue by yuefeng007** [JiangJuHong/FlutterTencentImPlugin#6]
### iphone 发送至android的。
文本/图片消息  已测试 无问题
语音消息无法送达，
视频和位置还没有测试 

以下是ios 的log日志
```
flutter: 准备调用 TencentImPlugin.sendMessage   ========start=======
flutter: 发送参数为
flutter: sessionId:15545111711
flutter: sessionType:SessionType.C2C
flutter: duration:8
flutter: path:file:///Users/a/Library/Developer/CoreSimulator/Devices/CF137EF9-71A6-434E-AE4E-B096ECDB43D2/data/Containers/Data/Application/8AB655E7-5208-4E71-9034-AB650DA511C2/Library/Caches/4ihvkfhpdomzxikcqtf_sound_.aac
flutter: 开始调用 TencentImPlugin.sendMessage   ========ing=======
flutter: 调用结束 TencentImPlugin.sendMessage   ========end=======
        [C5.1.1 4896F020-C1F2-48B3-9761-DE60AA80F7C0 192.168.1.123:49971<->111.161.64.123:443]
        Connected Path: satisfied (Path is satisfied), interface: en1
        Duration: 0.479s, DNS @0.005s took 0.004s, TCP @0.010s took 0.145s, TLS took 0.244s

        bytes in/out: 5031/1337, packets in/out: 6/4, rtt: 0.129s, retransmitted packets: 0, out-of-order packets: 0

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(7006, Execution Error, File check failed)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      TencentImPlugin.sendMessage (package:tencent_im_plugin/tencent_im_plugin.dart:73:24)
#3      _ChatBarState._getWindow.<anonymous closure> (package:chatpear/modules/home/widet_chat/chat_bar.dart:168:29)
#4      _WindowVoiceState.stopRecorder (package:chatpear/modules/home/widet_chat/window_voice.dart:192:16)
<asynchronous suspension>
#5      _WindowVoiceState.build.<anonymous closure> (package:chatpear/modules/home/widet_chat/window_voice.dart:85:9)
#6      DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:439:41)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#8      Dra<…>
        [C6.1.1 1BA48832-8376-4B7E-99C8-50AA0DBD750E 192.168.1.123:49973<->111.161.64.123:443]
        Connected Path: satisfied (Path is satisfied), interface: en1
        Duration: 0.303s, DNS @0.005s took 0.004s, TCP @0.010s took 0.048s, TLS took 0.137s
        bytes in/out: 3795/1165, packets in/out: 5/4, rtt: 0.050s, retransmitted packets: 0, out-of-order packets: 0
```

**Comment by JiangJuHong** [comment]
你好，你发送的是语音消息吗？请参考腾讯云错误码， 7006 代表错误信息如下：

![image](https://user-images.githubusercontent.com/17740963/77027848-42069e00-69d2-11ea-9688-b7bd714c23f3.png)

**Comment by yuefeng007** [comment]
难道是模拟器的原因，可是我现在没有办法真机测试。据说和ios系统有关，可能要等到 ios 发布13.4

**Comment by yuefeng007** [comment]
我看了 7006错误码说是空文件。但我可以确定 文件是有内容的。并且可以在我的模拟器本地播放

**Comment by JiangJuHong** [comment]
请仔细检查应用程序是否支持相关权限，并通过IOS相关代码进行调试
